# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/GUI.ui'
#
# Created: Mon Oct 27 12:05:09 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 654)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 191, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 221, 16))
        self.label_2.setObjectName("label_2")
        self.mainboardwidget = QtGui.QWidget(self.centralwidget)
        self.mainboardwidget.setGeometry(QtCore.QRect(0, 80, 100000, 100000))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainboardwidget.sizePolicy().hasHeightForWidth())
        self.mainboardwidget.setSizePolicy(sizePolicy)
        self.mainboardwidget.setMinimumSize(QtCore.QSize(100000, 100000))
        self.mainboardwidget.setCursor(QtCore.Qt.CrossCursor)
        self.mainboardwidget.setObjectName("mainboardwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.mainboardwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainboard = QtGui.QTableWidget(self.mainboardwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainboard.sizePolicy().hasHeightForWidth())
        self.mainboard.setSizePolicy(sizePolicy)
        self.mainboard.setMinimumSize(QtCore.QSize(10000000, 10000000))
        self.mainboard.setMaximumSize(QtCore.QSize(256, 16777215))
        self.mainboard.setProperty("cursor", QtCore.Qt.CrossCursor)
        self.mainboard.setStyleSheet("")
        self.mainboard.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.mainboard.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.mainboard.setObjectName("mainboard")
        self.mainboard.setColumnCount(0)
        self.mainboard.setRowCount(0)
        self.verticalLayout.addWidget(self.mainboard)
        self.solveButton = QtGui.QPushButton(self.centralwidget)
        self.solveButton.setGeometry(QtCore.QRect(200, 10, 80, 23))
        self.solveButton.setCursor(QtCore.Qt.ArrowCursor)
        self.solveButton.setDefault(True)
        self.solveButton.setFlat(False)
        self.solveButton.setObjectName("solveButton")
        self.cleanButton = QtGui.QPushButton(self.centralwidget)
        self.cleanButton.setGeometry(QtCore.QRect(200, 50, 81, 23))
        self.cleanButton.setDefault(True)
        self.cleanButton.setObjectName("cleanButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 20))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Map = QtGui.QAction(MainWindow)
        self.actionNew_Map.setObjectName("actionNew_Map")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.aboutASTAR = QtGui.QAction(MainWindow)
        self.aboutASTAR.setObjectName("aboutASTAR")
        self.menuArchivo.addAction(self.actionNew_Map)
        self.menuArchivo.addAction(self.actionExit)
        self.menuAbout.addAction(self.aboutASTAR)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Juan Luis Pérez", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Ingeniería del Conocimiento", None, QtGui.QApplication.UnicodeUTF8))
        self.solveButton.setText(QtGui.QApplication.translate("MainWindow", "Solve!", None, QtGui.QApplication.UnicodeUTF8))
        self.cleanButton.setText(QtGui.QApplication.translate("MainWindow", "Clean Map!", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArchivo.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "More", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Map.setText(QtGui.QApplication.translate("MainWindow", "New Map", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutASTAR.setText(QtGui.QApplication.translate("MainWindow", "About A Star Solver", None, QtGui.QApplication.UnicodeUTF8))

